stages:
- stage: Stop_agent
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - deployment: stop_agent
    displayName: Stop ADO self-hosted agent
    continueOnError: false
    environment: spoke13-kv
    strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureKeyVault@1
                displayName: "Pull KV secrets"
                inputs:
                  ConnectedServiceName: $(service_name)
                  KeyVaultName: $(key_vault_name)
                  SecretsFilter: '*'
                  RunAsPreJob: false 
              - task: AzureCLI@2
                displayName: 'Stop agent'
                inputs:
                  azureSubscription: $(azurerm-service-connection)
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az vm stop --name $(agent-name) --resource-group $(agent-rg)'