trigger:
- main

pool:
  name: azdevops1
  demands:
    - agent.name -equals atulvm-azdevops

variables:
- group: spoke13-kv

stages:
- template: pipeline-templates/addnsg.yaml
- template: pipeline-templates/valandplan.yaml
- template: pipeline-templates/approval.yaml
- template: pipeline-templates/apply.yaml
- template: pipeline-templates/delnsg.yaml
