stages:
- stage: add_rule
  jobs:
  - deployment: add_sg_rule
    displayName: Add inbound rule to controller nsg
    continueOnError: false
    environment: 'spoke13-kv'
    strategy:
        runOnce:
          deploy:
           steps:
             - task: AzureKeyVault@1
               displayName: "Pull KV secrets"
               inputs:
                 ConnectedServiceName: $(service_name)
                 KeyVaultName: $(key_vault_name)
                 SecretsFilter: '*'
                 RunAsPreJob: false 
             - task: AzureCLI@2
               displayName: 'set nsg'
               inputs:
                  azureSubscription: 'atulavtx-sst2'
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az network nsg rule create --name deploy13 --nsg-name $(controller-nsg) --priority 113 --resource-group $(controller-rg) --access Allow --protocol ''*'' --source-address-prefixes 4.234.217.149 --destination-port-ranges 80 443'
   
